apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: clean-k8s-log
  namespace: kube-system
spec:
  schedule: "0 0 */1 * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: clean-k8s-log
            image: cr.speakin.mobi/baseimg/tools:v1.0
            imagePullPolicy: IfNotPresent
            args:
            - /bin/sh
            - -c
            - curl -XDELETE http://elasticsearch:9200/k8s-`date +%Y.%m.%d -d '-3 days'` 
          restartPolicy: Never
