apiVersion: apps/v1
kind: Deployment
metadata:
  name: jz-monitor
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: jz-monitor
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jz-monitor
    spec:
      containers:
      - image: cr.xx.xx/jz/monitor
        imagePullPolicy: Always
        name: monitor
        # 容器启动脚本命令： python /jz_monitor/jz_monitor.py --promaddr http://192.168.0.51:9090 --job kube-jobs --namespace jz-base --ceph 192.168.0.106:9128 --mongo 192.168.0.106:9218
        command: ["python"]  # 使用command和args配合展示
        args: 
        - "/jz_monitor/jz_monitor.py" 
        - "--promaddr"
        - "http://192.168.23.1:9090"
        - "--job"
        - "kube-pods"
        - "--namespace"
        - "szjz"
        - "--ceph" 
        - "192.168.23.1:9128"
        - "--mongo" 
        - "192.168.23.21:9216"
        # 容器执行脚本的命令： python3 /scripts/scripts.py
        #- command:   # 可以将命令和参数按列表方式展示
        #    - python3
        #    - /scripts/scripts.py
      dnsPolicy: ClusterFirst
      restartPolicy: Always