apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: netshoot
  labels:
    k8s-app: netshoot
spec:
  selector:
    matchLabels:
      name: netshoot
  template:
    metadata:
      labels:
        name: netshoot
    spec:
      containers:
      - name: netshoot
        image: cr.speakin.mobi/baseimg/netshoot:latest